rathesDot/rathes.me

gatsby-config.js, package.json, yarn.lock
This PR adds the sitemap.xml to the website by adding the [gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/) for it.
=> Feature: Sitemap

src/pages/about.js
This PR adds the current book to the list and removes the remark from the finished ones.
=> Content: Update reading list

src/content/articles/en/review-2019.mdx, src/pages/about.js
This PR refactors the about page to use the `ReadingList` component. It implements the first part of #192
=> Refactor: Reading list

README.md
This PR fixes a small typo in the README.
=> ✏️ Fix typo

src/content/articles/en/review-2019.mdx, src/pages/about.js
This PR marks Origin as a finished book
=> Readinglist: Origin

src/components/BlogList/BlogList.js, src/pages/writings.js
This PR ensures that the blog list component is used on the writings page.
This PR entirely resolves #192
=> Refactor: BlogList

gatsby-config.js, package.json, src/components/BlogList/BlogList.js, src/content/articles/en/review-2019.mdx, src/pages/writings.js, yarn.lock
This PR introduces styled-components. It will slowly replace Tailwind CSS. It can be done step-by-step as this PR only refactors the `BlogList` component.
In the next step, I will introduce the theming part of styled-components.
This PR also fixes a small link bug from the previous PR #215 
This is the first part for #46
=> Feature: Introduce Styled Components

package.json, src/components/BlogList/BlogList.js, src/components/Link/Link.js, src/components/Link/index.js, src/components/Navigation/index.js, src/components/OverviewInfo/index.js, src/components/ReadingList/ReadingList.js, src/components/SayHi/index.js, src/pages/404.js, src/pages/legal.js, src/pages/work.js, src/pages/writings.js, src/templates/Blog/mdx.js, src/templates/Blog/remark.js, yarn.lock
As another step towards #46, this PR introduces a `Link` component and replaces all uses of Gatsbys `Link` or any `a` with this new component
=> Feature: `Link` component

src/pages/about.js
=> :one: Mention team ONE

renovate.json
Ensure that the versions are not pinned by renovate.
=> 🔧  Preserve semver range

src/components/Layout/index.js, src/components/Navigation/index.js, src/pages/index.js
This PR improves some sizing issues on mobile after the redesign
=> Improve: Mobile Sizes

src/pages/about.js
Improve the Grammar of the about me page using suggestions sent in by a follower on Twitter.
=> 🖋 Improve Grammar

LICENSE, src/components/Footer/index.js
This PR replaces all occurrences of 2019 with the current year
=> Fix: Year 2020

src/pages/talks/managing-time.js, src/pages/talks/meetings.js, src/pages/work.js
Add first drafts abstracts to talks that I want to talk about in the future.
=> Feature: Abstracts

src/pages/about.js
Adds "Sherlock Holmes: A Study in Scarlet" to currently reading books and moves "Library of Souls: The Third Novel of Miss Peregrine's Peculiar" to the finished ones
=> Update the readinglist

src/pages/about.js
This PR adds Eric Ries "The Lean Startup" to current books and moves Study in Scarlet to the finished books.
=> Reading: Add The Lean Startup to reading list

gatsby-config.js, package.json, src/components/fitness/Layout/index.js, src/components/fitness/Layout/reset.js, src/components/fitness/icons/ChevronLeft.js, src/components/fitness/icons/index.js, src/components/fitness/index.js, src/components/fitness/patterns/RestTime.js, src/components/fitness/patterns/Schedule.js, src/components/fitness/patterns/Workout.js, src/components/fitness/patterns/index.js, src/components/fitness/typography/BodyText.js, src/components/fitness/typography/Heading1.js, src/components/fitness/typography/Heading2.js, src/components/fitness/typography/Heading3.js, src/components/fitness/typography/Title.js, src/content/fitness/data.json, src/pages/fitness.js, yarn.lock
This PR adds a page that renders my fitness schedule.
=> Feature: Add my fitness schedule

gatsby-config.js, package.json, yarn.lock
Let's see if replacing the prefetch plugin fixes the issue that a few fonts are not loaded properly.
=> Fix: Loading Fonts

src/content/fitness/data.json, src/pages/fitness.js
=> Fitness: WOD 17/04

src/components/fitness/icons/BackArrowClock.js, src/components/fitness/icons/BaseIcon.js, src/components/fitness/icons/ChevronLeft.js, src/components/fitness/icons/index.js, src/content/fitness/data.json, src/pages/fitness.js
This PR adds an archive mode to show all workouts from the data set and not only the current week.
=> Feature: Add archive to fitness page

src/content/fitness/data.json
This WOD is to do as many burpees as possible in 15 minutes. At least rounds to pass the Burpril challenge.
=> 📈 Add WOD for 19/04

yarn.lock
=> ⬆️ yarn upgrade

src/components/Typography/TextSmall.tsx, src/pages/about.js
This PR adds the books that I have been reading in the past few months
=> Reading list update

src/pages/about.js
This PR adds the latest book that I'm reading to the list.
=> Feature: Update reading list

src/components/OverviewInfo/index.js, src/pages/index.js
This PR fixes the content stating that I'm living in London and not in Belgium anymore
=> Fix: Place

src/content/articles/en/review-2020.mdx, src/layouts/PageLayout/PageLayout.tsx
This PR adds the review for 2021.
=> Blog: Review 2020

src/pages/work.tsx
Add a small description about Maxout.
=> Content: Add Maxout

src/content/articles/en/managing-time.mdx
This PR improves the article. The wording seemed off at a few places so went through the article again.
=> ✏️ Improve article grammar

src/content/articles/externalLinks.ts
This PR adds the blog posts I wrote for Maxout to the list of writings.
=> Add Maxout articles

src/pages/about.tsx
This PR updates the reading list with the books that I'm reading right now
=> Feature: Read

src/pages/about.tsx
Finished reading Obamas book, adding a new one to the list
=> Update to reading list

src/content/blog/en/review-2021.mdx
This PR adds this years review blog post.
=> Review 2021

src/pages/about.tsx
Finished reading the last book I had on my list for this year 👍🏾
=> Books: Klara and the sun

data/books.json, src/components/Form/TextField.tsx, src/components/index.ts, src/pages/about.tsx, src/pages/reading-list.tsx
Adds a new page that contains all the books that I've been adding to the reading list so far. For now it's just a simple list but at some point, I might be interested in going a bit further with it adding ratings and comments
Closes #214
=> Feature: Reading list

src/components/Note/Note.tsx, src/pages/blog/[language]/[slug].tsx, tailwind.config.js
A small blog design update following some explorations on https://play.rathes.me/blog
=> Blog design update
